name: CI Pipeline - Tourist ML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install dvc[all]

    - name: Pull data with DVC
      run: |
        dvc pull -f

    - name: Run training script
      run: |
        python train_script.py

    - name: Commit updated model artifacts
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        dvc add random_forest_best.pkl
        git add random_forest_best.pkl.dvc dvc.lock
        git commit -m "Auto-update trained model"
        git push
